const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
async function api(path,options={}){const r=await fetch(path,options);let data;try{data=await r.json()}catch{throw new Error(`Resposta inválida (${r.status}).`)}if(!r.ok){const detail=Array.isArray(data.detail)?data.detail.map(x=>x.msg).join('; '):data.detail;throw new Error(data.erro||detail||`Erro ${r.status}`)}return data}
function showTab(id){$$('.panel,.tabs button').forEach(e=>e.classList.remove('active'));$('#'+id).classList.add('active');const tab=$(`[data-tab="${id}"]`);if(tab)tab.classList.add('active');if(id==='acervo')loadDocuments()}
$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
async function health(){try{const h=await api('/health');$('#status').textContent=`Online · ${h.documents} fonte(s)`;$('#status').classList.add('ok')}catch{$('#status').textContent='Offline'}}
async function loadDocuments(){const box=$('#documents');box.innerHTML='<p>Carregando…</p>';try{const docs=await api('/documents');box.innerHTML=docs.length?docs.map(d=>`<article class="document"><span class="level">NÍVEL ${d.source_level}</span><h3>${escapeHtml(d.title)}</h3><p class="meta">${escapeHtml(d.author)}${d.year?' · '+d.year:''} · Autenticidade: ${escapeHtml(d.authenticity_status)}</p>${d.origin?`<p class="meta"><b>Origem:</b> ${escapeHtml(d.origin)}</p>`:''}${d.provenance_note?`<p class="provenance"><b>Observação de procedência:</b> ${escapeHtml(d.provenance_note)}</p>`:''}<p>${escapeHtml(d.content.slice(0,280))}${d.content.length>280?'…':''}</p><div class="document-actions"><button onclick="editDocument('${d.id}')">Editar metadados</button><button onclick="viewHistory('${d.id}')">Ver histórico</button></div></article>`).join(''):'<div class="empty">O acervo ainda não possui documentos.</div>'}catch(e){box.innerHTML=`<p>${escapeHtml(e.message)}</p>`}}
window.editDocument=async id=>{try{const d=await api(`/documents/${id}`),f=$('#edit-form');['id','title','author','source_level','year','edition','origin','provenance_note','authenticity_status','rights_status'].forEach(k=>f.elements[k].value=d[k]??'');f.elements.responsible.value='';f.elements.justification.value='';$('#edit-message').textContent='';await loadHistory(id);showTab('editar')}catch(e){alert(e.message)}};
window.viewHistory=async id=>editDocument(id);
async function loadHistory(id){const box=$('#history');try{const rows=await api(`/documents/${id}/history`);box.innerHTML=rows.length?rows.map(r=>`<article class="history-item"><b>${label(r.field)}</b>: “${escapeHtml(value(r.old_value))}” → “${escapeHtml(value(r.new_value))}”<p class="meta">${escapeHtml(r.responsible)} · ${escapeHtml(r.changed_at)}</p><p>${escapeHtml(r.justification)}</p></article>`).join(''):'<div class="empty">Nenhuma alteração registrada.</div>'}catch(e){box.innerHTML=`<p>${escapeHtml(e.message)}</p>`}}
$('#edit-form').onsubmit=async e=>{e.preventDefault();const f=e.target,id=f.elements.id.value,keys=['title','author','source_level','year','edition','origin','provenance_note','authenticity_status','rights_status'],changes={};keys.forEach(k=>changes[k]=f.elements[k].value||null);if(changes.year)changes.year=Number(changes.year);const payload={changes,responsible:f.elements.responsible.value,justification:f.elements.justification.value},msg=$('#edit-message');msg.textContent='Salvando…';try{await api(`/documents/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});msg.textContent='Alteração salva e registrada no histórico.';await loadHistory(id)}catch(err){msg.textContent=err.message}};
$('#cancel-edit').onclick=()=>showTab('acervo');
$('#ask-form').onsubmit=async e=>{e.preventDefault();const box=$('#answer');box.classList.remove('hidden');box.innerHTML='<p>Pesquisando…</p>';try{const a=await api('/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:$('#question').value})});box.innerHTML=`<h3>${a.grounded?'Resposta fundamentada':'Fontes insuficientes'}</h3><p>${escapeHtml(a.answer)}</p>${a.citations.map(c=>`<blockquote><b>${escapeHtml(c.title)}</b> · ${escapeHtml(c.author)} · Nível ${c.source_level}<br>${escapeHtml(c.excerpt)}</blockquote>`).join('')}<p class="meta">${escapeHtml(a.observation||'')}</p>`}catch(err){box.innerHTML=`<p>${escapeHtml(err.message)}</p>`}};
$('#document-form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target),payload=Object.fromEntries(form.entries());if(payload.year)payload.year=Number(payload.year);else delete payload.year;const msg=$('#document-message');msg.textContent='Salvando…';try{await api('/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});msg.textContent='Fonte salva permanentemente.';e.target.reset();health()}catch(err){msg.textContent=err.message}};
$$('[data-try]').forEach(b=>b.onclick=async()=>{const path=b.dataset.try==='health'?'/health':'/documents';try{$('#api-output').textContent=JSON.stringify(await api(path),null,2)}catch(e){$('#api-output').textContent=e.message}});
function label(k){return({title:'Título',author:'Autoria',source_level:'Nível da fonte',year:'Ano',edition:'Edição',origin:'Origem',provenance_note:'Observação de procedência',authenticity_status:'Autenticidade',rights_status:'Direitos/autorização'})[k]||k}function value(v){return v===null?'não informado':String(v)}function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}health();
